name: rai-sdk-javascript workflow

on: [push]

jobs:
  sdk:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.0

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Types check
        run: npm run tscheck

      - name: Tests
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          CLIENT_CREDENTIALS_URL: ${{ secrets.CLIENT_CREDENTIALS_URL }}
        run: npm run test

      - name: Build
        run: npm run build

      - name: Bundle Test
        run: npm run test:bundle
