name: rai-sdk-javascript workflow

on: [push]

jobs:
  sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Types check
        run: npm run tscheck
