name: rai-sdk-javascript workflow

on: [push]

jobs:
  sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Show node version number
        run: echo "Version is ${{ steps.package-node-version.outputs.version }}"

      - name: Setup Node.js ${{ steps.package-node-version.outputs.version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ steps.package-node-version.outputs.version }}

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Types check
        run: npm run tscheck
