name: rai-sdk-javascript workflow

on: [push]

jobs:
  sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0

      - name: Install dependencies
        run: npm ci

      - name: ESLint
        run: npm run lint

      - name: Types check
        run: npm run tscheck

      - name: Tests
        uses: ./.github/actions/test
        with:
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          client_credentials_url: ${{ secrets.CLIENT_CREDENTIALS_URL }}

      - name: Build
        run: npm run build

      - name: Bundle Test
        run: npm run test:bundle
